config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'invitations' }

  notify_to :users

  resources :areas, only: [:show, :update, :edit, :destroy] do
    resources :tasks, only: [ :new, :create, :update, :destroy, :edit]
  end

  root to: "pages#home"

  # devise_scope :user do
  #   root to: 'devise/sessions#new'
  # end

  resources :flatmembers, only: [:destroy]
  resources :chatrooms


  resources :flats do
    get 'members', to: 'flatmembers#invite'
    post 'invitations', to: 'flatmembers#send_invitations'

    resources :users
    resources :bills

    resources :events do
      resources :participations
    end

    resources :flatmembers, only: :update

    resources :areas do
      resources :tasks
    end

    resources :chatrooms, only: [:index, :new, :create] do
      resources :messages, only: [:create]
    end

  end

  resources :bills, only: [] do
    resources :payments, only: [:update]
  end


  resources :components
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/flat.rb
class Flat < ApplicationRecord
  has_many :flatmembers, dependent: :destroy
  has_many :users, through: :flatmembers
  has_many :bills
  has_many :events
  has_many :areas
  has_many :chatrooms, dependent: :destroy

  validates :name, presence: true
  validates :name, length: { minimum: 2 }
  validates :full_address, presence: true

  after_create :create_chatroom

  def create_chatroom
    Chatroom.create(flat_id: self.id, name: "#{self.name} chat 💬")
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :update, :set_flatmembers, :destroy]
  skip_before_action :verify_authenticity_token, only: [:update]

  def show
    @flat_flatmembers =  @flat.flatmembers
    @flat_areas = @flat.areas

    user = current_user
    authorize @flat

    @notifications = current_user.notifications.limit(15).order(created_at: :desc)
  end

  def new
    @flat = Flat.new
    @user = current_user
  end

  def create
    @flat = Flat.create(flat_params)
    @member = Flatmember.create(user: current_user, flat: @flat, is_admin: true)

    if @flat.save && @member.save
      redirect_to flat_path(current_user.flats.last)
    else
      render "flats/new"
    end
  end

  def destroy
    @flat.destroy
    authorize @flat

    redirect_to flats_path
  end


  def update
    @flat.update(flat_params)
      respond_to do |format|
        format.html
        format.json { render json: { flat: @flat } }
      end
    authorize @flat
  end

  private

  def set_flat
      @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :full_address)
  end
end

app/views/flats/_form_flat.html.erb
<%= simple_form_for [@flat] do |f| %>
  <h2>Create a new Flat</h2>
  <%= f.input :name, placeholder: "Flat's Name", label: false %>
  <%= f.input :full_address, placeholder: "Full address", label: false, input_html: { data: { target: 'autocomplete.input'} } %>
  <%= f.submit "Create flat", class: "btn btn-success text-white"%>
<% end %>

app/views/flats/_notification.html.erb
<%= link_to ApplicationController.helpers.notification_path(notification), class: "secondary-link text-decoration-none " do %>
  <div class="row calendar-card-white my-3 notification <%= "notification-background-seen" if !(notification.opened_at.nil?) %>">
    <div class="col-2 justify-content-start align-items-center d-flex">
      <!-- AVATAR -->
      <% if ApplicationController.helpers.notification_user(notification)&.picture&.attached? %>
        <%= cl_image_tag ApplicationController.helpers.notification_user(notification).picture.key, class: 'avatar-secondary-gray' %>
      <% else %>
        <i class="fas fa-user-circle fa-2x"></i>
      <% end %>
    </div>
    <div class="col-8 justify-content-start align-items-start">
      <!-- USER NAME -->
      <% if notification.notifiable_type != "Message" %>
        <h6><%= ApplicationController.helpers.notification_user(notification)&.first_name %></h6>
      <% end %>
      <!-- NOTIFICATION NAME -->
      <p><%= ApplicationController.helpers.notification_message(notification).try(:html_safe) %></p>
      <p class="smaller-text"><%= distance_of_time_in_words(Time.now, notification.created_at)%> ago</p>
    </div>
    <div class="col-2 justify-content-end align-items-center d-flex">
      <i class="<%= NOTIFICATIONS_ICONS[notification.notifiable_type.to_sym] %> fa-2x text-primary"></i>
    </div>
  </div>
<% end %>

app/views/flats/_notifications.html.erb
<div class="container" id="notifications-wrapper">
  <div class="row">
    <div class="col-12">
      <% if @notifications.length == 0 %>
        <h3 class="my-4">You don't have any notifications</h3>
      <% else %>
        <div
          data-target="notifications.container"
          data-flat-id="<%= @flat.id %>"
          data-user-id="<%= current_user.id %>"
        >
          <% @notifications.each do |notification| %>
            <%= render 'notification', notification: notification %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 text-center">
      <h1 class="mb-4">Create a flat 🏠</h1>
      <div>
        <%= link_to image_tag('add-button.svg'), new_flat_path %>
        <p>Add new flat</p>
      </div>
    </div>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8">
      <div data-controller="autocomplete">
        <%= render 'form_flat' %>
      </div>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<!-- FLAT NAME -->
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8">
      <div class="card-white">
        <div class="container">
          <div class="row">
            <div class="col-12" data-controller="flats">
              <div
                data-action="click->flats#changeNameToInput"
                data-id="<%= @flat.id %>"
                data-target="flats.title"
              >
                <h1 class="text-center mb-1">🏡 <%= @flat.name %></h1>
              </div>
              <p class="text-center secondary-p"> <i class="fas fa-map-marker-alt text-orange"></i> <%= @flat.full_address %></p>
            </div>
          </div>

          <!-- AVATARS -->
          <div class="row justify-content-center">
            <div class="col-12 justify-content-center d-flex">
              <div class="d-flex flex-column align-items-center">
                <!-- CURRENT USER AVATAR -->
                <div id="dropdown-menu-custom"  class="dropdown">
                  <button role="button" type="button" class="btn dropdown p-0" data-toggle="dropdown">
                    <% if current_user.picture.attached? %>
                      <%= cl_image_tag current_user.picture.key, :quality=>100, class: 'avatar-primary-gray' %>
                    <% else %>
                      <i class="fas fa-user-circle fa-3x"></i>
                    <% end %>
                      <p>You</p>
                  </button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" data-remote="true">
                    <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
                    <% if current_user.flatmembers.first.is_admin == true %>
                      <%= link_to "Delete Flat", flat_path(@flat), method: :delete, data: { confirm: "Are you sure?" }, class: "dropdown-item" %>
                    <% end %>
                    <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="row justify-content-center">
            <% @flat_flatmembers.each do |flatmember| %>
              <% if flatmember.user.id != current_user.id %>
                <div class="col-3 justify-content-center d-flex">
                  <div class="d-flex flex-column align-items-center">
                    <!-- FLATMEMBERS AVATAR AND NAME -->
                    <div id="dropdown-menu-custom" class="dropdown">
                      <button role="button" type="button" class="btn dropdown p-0" data-toggle="dropdown">
                        <% if flatmember.user.picture.attached? %>
                          <%= cl_image_tag flatmember.user.picture.key, :quality=>100, class: 'avatar-secondary-gray' %>
                        <% else %>
                          <i class="fas fa-user-circle fa-2x"></i>
                        <% end %>
                          <p><%= flatmember.user.first_name %></p>
                      </button>
                      <% if current_user.flatmembers.first.is_admin == true %>
                        <div class="dropdown-menu p-1 text-center" aria-labelledby="dropdownMenuButton" data-remote="true">
                          <%= link_to "Delete member",
                            flatmember_path(flatmember),
                            class: "dropdown-item",
                            method: :delete,
                            data: { confirm: "Are you sure?",
                            } %>
                          <% if flatmember.is_admin %>
                            <p class="dropdown-item m-0 background-admin">Admin</p>
                          <% else %>
                            <%= simple_form_for flatmember, class: "dropdown-item background-none p-0 m-0", url: flat_flatmember_path(@flat, flatmember), method: :patch do |f| %>
                              <%= f.input :is_admin, :as => :hidden, :input_html => { :value => :true } %>
                              <%= f.submit "Make admin", class: "dropdown-item submit-tag p-0" %>
                            <% end %>
                          <% end %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>

          <div class="row">
            <div class="col-12 justify-content-center align-items-center d-flex mt-3">
              <%= link_to "+ Add Members", flat_members_path(@flat), class: "btn btn-info shadow text-orange px-4" %>
            </div>
          </div>

        </div>
      </div>

    </div>
  </div>
</div>

<!-- NOTIFICATIONS NAME -->

  <div class="container mt-5 mb-1">
    <div class="row justify-content-center">
      <div class="col-12 col-md-8">
        <h4 class="text-start">Latest changes</h4>
         <!-- NOTIFICATIONS -->
        <%= render "notifications" %>
      </div>
    </div>
  </div>