config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'invitations' }

  notify_to :users

  resources :areas, only: [:show, :update, :edit, :destroy] do
    resources :tasks, only: [ :new, :create, :update, :destroy, :edit]
  end

  root to: "pages#home"

  # devise_scope :user do
  #   root to: 'devise/sessions#new'
  # end

  resources :flatmembers, only: [:destroy]
  resources :chatrooms


  resources :flats do
    get 'members', to: 'flatmembers#invite'
    post 'invitations', to: 'flatmembers#send_invitations'

    resources :users
    resources :bills

    resources :events do
      resources :participations
    end

    resources :flatmembers, only: :update

    resources :areas do
      resources :tasks
    end

    resources :chatrooms, only: [:index, :new, :create] do
      resources :messages, only: [:create]
    end

  end

  resources :bills, only: [] do
    resources :payments, only: [:update]
  end


  resources :components
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar-smartphone.html.erb
<div class="navbar-smartphone">

  <%= link_to flat_path(@flat) do %>
    <% css_class_flat = controller?('flats') ? "text-orange" : "text-gray" %>
    <div class="navbar-home <%= css_class_flat %>">
      <i class=" <%= "#{ICONS_NAVBAR[:home]}" %> "></i>
      <p>Home</p>
    </div>
  <% end %>

  <%= link_to flat_bills_path(@flat) do %>
    <% css_class_bill = controller?('bills') ? "text-orange" : "text-gray" %>
    <div class="navbar-bills <%= css_class_bill %>">
      <i class=" <%= "#{ICONS_NAVBAR[:bill]}" %> "></i>
      <p>Bills</p>
    </div>
  <% end %>

  <%= link_to flat_areas_path(@flat, @area) do %>
    <% css_class_task = controller?('areas') ? "text-orange" : "text-gray" %>
    <div class="navbar-tasks <%= css_class_task %> ">
      <i class=" <%= "#{ICONS_NAVBAR[:task]}" %> "></i>
      <p>Tasks</p>
    </div>
  <% end %>

  <%= link_to flat_events_path(@flat, @event) do %>
    <% css_class_event = controller?('events') ? "text-orange" : "text-gray" %>
    <div class="navbar-events <%= css_class_event %> ">
      <i class=" <%= "#{ICONS_NAVBAR[:event]}" %> "></i>
      <p>Events</p>
    </div>
  <% end %>

  <% notifications_count = current_user.notifications.where(notifiable_type: 'Message', opened_at: nil).count %>
  <% css_class_chatroom = controller?('chatrooms') ? "text-orange" : "text-gray" %>
  <% if notifications_count == 0 %>
    <%= link_to flat_chatrooms_path(@flat) do %>
        <div class="navbar-chat <%= css_class_chatroom %> ">
          <i class=" <%= "#{ICONS_NAVBAR[:chatroom]}" %> "></i>
          <p>Chat</p>
        </div>
    <% end %>
  <% else %>
    <%= link_to flat_chatrooms_path(@flat) do %>
        <div class="navbar-chat <%= css_class_chatroom %> ">
          <sup class="smartphone"> <span class="badge badge-pill badge-danger text-top notification-badge"> <%= notifications_count %> </span> </sup>
          <i class=" <%= "#{ICONS_NAVBAR[:chatroom]}" %> "> </i>
          <p>Chat</p>
        </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-lewagon navbar-flatcares">

    <%= link_to "/", class: "navbar-brand" do %>
      <h3 class="m-0">flatcares.com</h3>
    <% end %>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if (user_signed_in?) && (!current_user.flats.empty?) && (!@flat.nil?) %>
        <li class="nav-item">
          <% css_class_flat = controller?('flats') ? "nav-link text-orange" : "nav-link text-gray" %>
          <%= link_to "Home", flat_path(@flat), class: "#{css_class_flat}" %>
        </li>
        <li class="nav-item">
          <% css_class_bill = controller?('bills') ? "nav-link text-orange" : "nav-link text-gray" %>
          <%= link_to "Bills", flat_bills_path(@flat), class: "#{css_class_bill}" %>
        </li>
        <li class="nav-item">
          <% css_class_area = controller?('areas') ? "nav-link text-orange" : "nav-link text-gray" %>
          <%= link_to "Tasks", flat_areas_path(@flat), class: "#{css_class_area}" %>
        </li>
        <li class="nav-item">
          <% css_class_event = controller?('events') ? "nav-link text-orange" : "nav-link text-gray" %>
          <%= link_to "Events", flat_events_path(@flat), class: "#{css_class_event}" %>
        </li>
        <div class="nav-item">
          <% css_class_chatroom = controller?('chatrooms') ? "nav-link text-orange" : "nav-link text-gray" %>
          <% notifications_count = current_user.notifications.where(notifiable_type: 'Message', opened_at: nil).count %>
          <% if notifications_count == 0 %>
            <%= link_to "Chat", flat_chatrooms_path(@flat), class: "#{css_class_chatroom}" %>
          <% else %>
            <div class="d-flex justify-content-between align-items-center">
              <%= link_to flat_chatrooms_path(@flat), class: "#{css_class_chatroom}" do %>
                <div>Chat <sup> <span class="badge badge-pill badge-danger text-top"> <%= notifications_count %> </span> </sup> </div>
              <% end %>
            </div>
          <% end %>
        </div>

      <% elsif (user_signed_in?) && (@flats.nil?) %>
        <li class="nav-item dropdown">
          <button role="button" type="button" class="btn dropdown p-0" data-toggle="dropdown">
            <% if current_user.picture.attached? %>
              <%= cl_image_tag current_user.picture.key, :quality=>100, class: "avatar-secondary-orange", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <i class="fas fa-user-circle fa-2x" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" ></i>
            <% end %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </button>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>