config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'invitations' }

  notify_to :users

  resources :areas, only: [:show, :update, :edit, :destroy] do
    resources :tasks, only: [ :new, :create, :update, :destroy, :edit]
  end

  root to: "pages#home"

  # devise_scope :user do
  #   root to: 'devise/sessions#new'
  # end

  resources :flatmembers, only: [:destroy]
  resources :chatrooms


  resources :flats do
    get 'members', to: 'flatmembers#invite'
    post 'invitations', to: 'flatmembers#send_invitations'

    resources :users
    resources :bills

    resources :events do
      resources :participations
    end

    resources :flatmembers, only: :update

    resources :areas do
      resources :tasks
    end

    resources :chatrooms, only: [:index, :new, :create] do
      resources :messages, only: [:create]
    end

  end

  resources :bills, only: [] do
    resources :payments, only: [:update]
  end


  resources :components
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bill.rb
class Bill < ApplicationRecord
  include Notifiable

  belongs_to :user
  belongs_to :flat
  belongs_to :paying_user, class_name: 'User'

  has_one_attached :invoice
  has_many :payments, dependent: :destroy

  enum category: CATEGORIES

  validates :name, presence: true
  validates :category, presence: :true
  validates :amount_cents, presence: true
  validates :due_date, presence: true

  after_create :create_payments
  after_update :update_payments

  monetize :amount_cents


  def status
    if (Date.today > self.due_date) && self.payments.where(paid: false).size > 0
      "Overdue"
    elsif self.payments.where(paid: true).count == self.payments.count
      "Paid"
    else
      "Pending"
    end
  end

  include PgSearch::Model
  scope :by_category, -> (category) { where(category: category) }
  scope :by_amount, -> (amounts) { where('amount_cents >= ? AND amount_cents <= ?', amounts.first * 100, amounts.last * 100) }
  scope :by_pending, -> () { where('due_date >= ?', Date.today) }
  scope :by_overdue, -> () { where('due_date <= ?', Date.today) }

  private

  def create_payments

    if sharing_member[0] == 0
      # SELECT ALL
      amount_by_users_all = ActionView::Base.new.humanized_money(amount).to_f / flat.users.count
      Payment.create(user_id: paying_user_id, bill_id: id, amount: amount_by_users_all, paid: true)
      flat.users.where.not(id: paying_user_id).each do |user|
        Payment.create(user_id: user.id, bill_id: id, amount: amount_by_users_all)
      end
    else
      # CUSTOMIZE PART
      amount_by_users_customize = ActionView::Base.new.humanized_money(amount).to_f / sharing_member.count
      if sharing_member.include?(paying_user_id)
        Payment.create(user_id: paying_user_id, bill_id: id, amount: amount_by_users_customize, paid: true)

        (sharing_member - [paying_user_id]).each do |user|
          Payment.create(user_id: user, bill_id: id, amount: amount_by_users_customize)
        end
      else
        sharing_member.each do |user|
          Payment.create(user_id: user, bill_id: id, amount: amount_by_users_customize)
        end
      end
    end
  end

  def update_payments
    payments.destroy_all
    create_payments
  end

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :update, :edit, :destroy]
  before_action :set_bills, only: :index
  before_action :check_display_index, only: :index

  def index
    @flat = policy_scope(Flat).find(params[:flat_id])

    @bills = Bill.where(flat_id: params[:flat_id])


    if params[:category].present? && params[:category] != ""
      @bills = @bills.by_category(params[:category])
    end

    if params[:amount_cents].present? && params[:amount_cents] != ""
      @bills = @bills.by_amount(@amounts[params[:amount_cents].to_sym].to_a)
    end

    if (params[:pending].present? && params[:pending] == "true") && (params[:overdue].present? && params[:overdue] == "true")
      @bills = @bills.by_pending + @bills.by_overdue
    elsif params[:pending].present? && params[:pending] == "true"
      @bills = @bills.by_pending
    elsif params[:overdue].present? && params[:overdue] == "true"
      @bills = @bills.by_overdue
    end

    respond_to do |format|
      format.html
      format.json {
        render json: {
          bills: json_with_html(@bills)
        }
      }
    end

  end

  def show
    authorize @bill
    @notification = current_user.notifications.find_by(notifiable_id: params[:id], notifiable_type: "Bill")

    if @notification
      @notification.update opened_at: Date.today
    end

    @flat = Flat.find(params[:flat_id])
    @chatroom = @flat.chatrooms.first
  end

  def new
    @flat = policy_scope(Flat).find(params[:flat_id])
    @users = @flat.users
    @user = current_user
    @bill = Bill.new
    @payment = Payment.new
  end

  def create
    @bill = Bill.new(bill_params)
    @bill.user_id = current_user.id

    @flat = policy_scope(Flat).find(params[:flat_id])
    @bill.flat_id = @flat.id

    if @bill.save
      redirect_to flat_bill_path(@flat, @bill)
    else
      render "bills/new"
    end
  end

  def edit
    @flat = Flat.find(params[:flat_id])
    authorize @bill
  end

  def update
    @flat = policy_scope(Flat).find(params[:flat_id])
    if @bill.update(bill_params)
      redirect_to flat_bill_path
    else
      render "bills/new"
    end
  end

  def destroy
    @flat = Flat.find(params[:flat_id])
    @bill.destroy
    authorize @bill
    redirect_to flat_bills_path
  end

  private


  def bill_params
    params.require(:bill).permit(
      :name,
      :amount,
      :due_date,
      :paying_user_id,
      :invoice,
      :category,
      :sharing_member, sharing_member: []
    )
  end

  def set_bill
    @bill = Bill.find(params[:id])
  end

  def set_bills
    @bills = Bill.all

    @categories = @bills.map { |bill| bill.category }
    @categories.uniq!

    @dates = @bills.map { |bill| bill.due_date }
    @dates.uniq!

    @amounts = {
      "€0 - €50": [0, 50],
      "€50 - €100": [50, 100],
      "€100 - €150": [100, 150],
      "€150 - €200": [150, 200],
      "€200 - €250": [200, 250],
      "€250 +": [250, 50000000]
    }
  end

  def check_display_index
    @your_index = !params[:user_id].present?
  end

  def json_with_html(bills)
    bills.map do |bill|
      bill_hash = bill.as_json

      bill_hash.merge({
        html: render_to_string(partial: "bills/bill_card", locals: { bill: bill }, formats: :html)
      })
    end
  end
end

app/views/bills/_bill_card.html.erb
<%= link_to flat_bill_path(@flat, bill), class: "secondary-link text-decoration-none" do %>
  <div class="<%= (bill.status == "Pending") || (bill.status == "Overdue") ? 'card-half-gray' : 'card-half-orange' %>">
    <%= render 'bill_name_icon', bill: bill %>
    <p><%=bill.due_date%></p>
    <div class="d-flex justify-content-between align-items-end">
      <% if bill.status == "Overdue" %>
        <p class="secondary-p m-0 text-danger"><br><%=bill.status %></p>
      <% else %>
        <p class="secondary-p m-0"><br><%=bill.status %></p>
      <% end %>
      <h3 class="m-0"><%= humanized_money_with_symbol(bill.amount) %></h3>
    </div>
  </div>
<% end %>

app/views/bills/_bill_name_icon.html.erb
<div class="d-flex justify-content-between">
  <h3><%=bill.name.capitalize%></h3>
  <h3><i class="<%= BILL_ICONS[bill.category.downcase.to_sym] %>"></i></h3>
</div>

app/views/bills/_bills_filter.html.erb
<%= form_tag flat_bills_path, method: :get, data: { target: "bills.form", flat: @flat.id } do %>

  <div class="btn-group mb-2 mr-2 select dropdown ">
    <button class="dropdown-toggle btn inactive-filter border-0" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Bill type
    </button>

    <div class="dropdown-menu filter-dropdown" aria-labelledby="dropdownMenuButton">
      <% @categories.each do |category| %>
        <button
          data-action="click->bills#filterBills"
          data-filter="category"
          data-value="<%= category %>"
          class="inactive-filter border-0 dropdown-item"
        >
          <%= category %>
        </button>
      <% end %>
    </div>
  </div>


  <div class="btn-group mb-2 mr-2 select dropdown ">
    <button class="dropdown-toggle btn inactive-filter border-0" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Bill amount
    </button>

    <div class="dropdown-menu filter-dropdown" aria-labelledby="dropdownMenuButton">
      <% @amounts.keys.each do |amount| %>
        <button
          data-action="click->bills#filterBills"
          data-filter="amount_cents"
          data-value="<%= amount %>"
          class="inactive-filter border-0 dropdown-item"
        >
          <%= amount %>
        </button>
      <% end %>
    </div>
  </div>

  <div class="btn-group mb-2 mr-2 select dropdown ">
    <button data-text="Bill status" class="dropdown-toggle btn inactive-filter border-0" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Bill status
    </button>
    <div class="dropdown-menu filter-dropdown" aria-labelledby="dropdownMenuButton">
      <button data-action="click->bills#filterBills" data-filter="pending" class="inactive-filter border-0 dropdown-item">
        Pending
      </button>
      <button data-action="click->bills#filterBills" data-filter="overdue" class="inactive-filter dropdown-item border-0">
        Overdue
      </button>
    </div>
  </div>

  <div class="btn-group mb-2 mr-2 button">
    <%= link_to "Reset Filters", flat_bills_path %>
  </div>
<% end %>

app/views/bills/_form_bill.html.erb
<%= simple_form_for [@flat, @bill] do |f| %>
  <h2>Create a new Bill</h2>
  <%= f.input :name,
              required: true,
              placeholder: "Bill's Name",
              label: false
              %>
  <%= f.input :category,
              collection: CATEGORIES,
              required: true,
              include_blank: "Bill's Category",
              label: false
              %>
  <%= f.input :amount,
              as: :float,
              required: true,
              placeholder: 'How much was the payment?',
              label: false,
              input_html:
                { min: 0,
                  value: nil,
                  class: 'form-control numeric float optional'
                }
              %>
  <%= f.input :due_date,
              required: true,
              placeholder: "Year",
              class: "form-control"
              %>
  <%= f.association :paying_user,
                    collection: @flat.users,
                    required: true,
                    label_method: lambda { |user| user.first_name.nil? ? "#{user.email}" : "#{user.first_name}" },
                    include_blank: "Who paid the bill?",
                    label: false
                    %>

  <%= f.input :sharing_member,
              as: :check_boxes,
              collection: [User.new(id: 0, first_name: 'All')] + @flat.users,
              input_html: {data: {behaviour: 'select-all'}},
              required: true,
              value_method: :id,
              include_blank: false,
              include_hidden: false,
              label_method: lambda { |user| user.first_name.nil? ? "#{user.email}" : "#{user.first_name}" },
              label: "Who is part of the bill?"
              %>

  <%= f.input :invoice,
              as: :file,
              label: false
              %>
  <%= f.submit "Submit the bill", class: "btn btn-success text-white"%>
<% end %>

app/views/bills/_form_bill_has_paid.html.erb
<%= simple_form_for payment, class: "background-none p-0", url: bill_payment_path(@bill, payment), method: :patch do |f| %>
  <%= f.input :paid, :as => :hidden, :input_html => { :value => :true }, remote: true %>
  <%= f.submit "Mark as paid", class: "btn btn-info shadow text-orange px-3" %>
<% end %>

app/views/bills/_form_bill_hasnt_paid.html.erb
<%= simple_form_for payment, class: "background-none", url: bill_payment_path(@bill, payment), method: :patch do |f| %>
  <%= f.input :paid, :as => :hidden, :input_html => { :value => :false }, remote: true %>
  <%= f.submit "Mark as unpaid", class: "btn btn-link primary-link margin-changes" %>
<% end %>

app/views/bills/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <%= simple_form_for [@flat, @bill] do |f| %>
        <h2>Edit a Bill</h2>
        <%= f.input :name,
              required: true,
              placeholder: "Bill's Name",
              label: false
              %>
        <%= f.input :category,
                    collection: CATEGORIES,
                    required: true,
                    include_blank: "Bill's Category",
                    label: false
                    %>
        <%= f.input :amount,
                    as: :float,
                    required: true,
                    placeholder: 'How much was the payment?',
                    label: false,
                    input_html:
                      { min: 0,
                        value: nil,
                        class: 'form-control numeric float optional'
                      }
                    %>
        <%= f.input :due_date,
                    required: true,
                    placeholder: "Year",
                    class: "form-control"
                    %>
        <%= f.association :paying_user,
                          collection: @flat.users,
                          required: true,
                          label_method: :first_name,
                          include_blank: "Who paid the bill?",
                          label: false
                          %>

        <%= f.input :sharing_member,
                    as: :check_boxes,
                    collection: [User.new(id: 0, first_name: 'All')] + @flat.users,
                    input_html: {data: {behaviour: 'select-all'}},
                    required: true,
                    value_method: :id,
                    include_blank: false,
                    include_hidden: false,
                    label_method: lambda { |user| user.first_name.nil? ? "#{user.email}" : "#{user.first_name}" },
                    label: "Who is part of the bill?"
                     %>

        <%= f.input :invoice,
                    as: :file,
                    label: false
                    %>
        <%= f.submit "Submit the bill", class: "btn btn-success text-white"%>
      <% end %>
    </div>
  </div>
</div>

app/views/bills/index.html.erb
<div data-controller="bills">
  <% if @your_index %>

    <div class="container mt-4">
      <div class="row justify-content-center">
        <div class="col-12 col-md-8">
        <div class="d-flex justify-content-between align-items-center">
          <h1 class="ml-3">House Bills</h1>
          <%= link_to image_tag('add-button.svg'), new_flat_bill_path %>
        </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="row justify-content-center">
        <div class="col-12 col-md-8">
          <div class="pt-2">
            <%= render "bills_filter" %>
          </div>
        </div>
      </div>
    </div>

    <div class="container mt-3">
      <div class="row justify-content-center">
        <div class="col-12 col-md-8">
          <div class="cards-grid" data-target="bills.bills">
            <% @bills.order('due_date desc').each do |bill| %>
              <%= render 'bill_card', bill: bill %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  <% end %>

</div>

app/views/bills/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <%= render 'form_bill' %>
    </div>
  </div>
</div>

app/views/bills/show.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8">
      <div class="d-flex justify-content-between align-items-start">
        <div class="mr-4">
          <h1><%= @bill.name %></h1>
          <p> <%= @bill.due_date %> </p>
        </div>
        <div>
          <%= link_to edit_flat_bill_path(@flat, @bill) do %>
            <i class="far fa-edit secondary-link"></i>
          <% end %>
          |
          <%= link_to flat_bill_path(@flat, @bill), method: :delete, data: { confirm: "Are you sure?" } do %>
            <i class="far fa-trash-alt secondary-link"></i>
          <% end %>
        </div>
      </div>
      <div class="d-flex align-items-end flex-column">
        <h2>Total <%= humanized_money_with_symbol(@bill.amount) %> </h2>
        <p><i> <strong> Paid by <%= @bill.paying_user.first_name %> </strong></i></p>
      </div>
      <div class="d-flex justify-content-between align-items-center">
        <%= link_to "< Go to Bills", flat_bills_path, class: "primary-link" %>
        <% if @bill.invoice.attached? %>
          <a href="<%= cl_image_path @bill.invoice.key %>" class="my-3" target="_blank">Invoice file</a>
        <% else %>
          <p class="mt-3">No invoice attached</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8">
      <% @bill.payments.order("created_at asc").each do |payment| %>
        <div class="<%= (payment.user_id == @bill.paying_user_id) || (payment.paid == true) ? 'expenses-card-white' : 'expenses-card-gray' %>">
          <div class="d-flex justify-content-between" id="payment-<%= payment.id %>">
            <div class="d-flex align-items-center">
              <%if payment.user.picture.attached?%>
                  <%= cl_image_tag payment.user.picture.key, :quality=>100, class: 'avatar-secondary-orange mr-2' %>
              <%else%>
                <i class="fas fa-user-circle fa-2x mr-2"></i>
              <%end%>
              <h3> <%= payment.user.first_name %></h3>
            </div>
              <% if (payment.paid == true) & (payment.user_id == @bill.paying_user_id) %>
                <div class="text-right">
                  <h2> <%= humanized_money_with_symbol(payment.amount) %> </h2>
                  <p class= "secondary-p mb-0">Has paid</p>
                </div>
              <% elsif (payment.paid == false) & (payment.user_id != @bill.paying_user_id) %>
                <div class="text-right">
                  <h2> <%= humanized_money_with_symbol(payment.amount) %> </h2>
                  <p class= "secondary-p">Has to pay to <%= @bill.paying_user.first_name %> </p>
                </div>
              <% else %>
                  <div class="text-right">
                    <h2> <%= humanized_money_with_symbol(payment.amount) %> </h2>
                    <p class= "secondary-p">Has paid to <%= @bill.paying_user.first_name %></p>
                  <% if ((current_user.id == payment.user_id) || (current_user.id == @bill.paying_user_id)) %>
                    <%= render 'form_bill_hasnt_paid', payment: payment %>
                  <% end %>
                  </div>
              <% end %>
            </div>
            <% if ((payment.user_id != @bill.paying_user_id) && (payment.paid == false)) %>
              <% if (current_user.id == @bill.paying_user_id) %>
                <div class="d-flex justify-content-between align-items-center background-none">
                  <%= link_to "Request Payment", flat_bills_path, class: "secondary-link" %>
                  <%= render 'form_bill_has_paid', payment: payment %>
                </div>
              <% elsif (current_user.id == payment.user_id) %>
                <div class="background-none d-flex align-items-end flex-column">
                  <%= render 'form_bill_has_paid', payment: payment %>
                </div>
              <% end %>
            <% end %>
          </div>
      <% end %>
    </div>
  </div>
</div>