config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'invitations' }

  notify_to :users

  resources :areas, only: [:show, :update, :edit, :destroy] do
    resources :tasks, only: [ :new, :create, :update, :destroy, :edit]
  end

  root to: "pages#home"

  # devise_scope :user do
  #   root to: 'devise/sessions#new'
  # end

  resources :flatmembers, only: [:destroy]
  resources :chatrooms


  resources :flats do
    get 'members', to: 'flatmembers#invite'
    post 'invitations', to: 'flatmembers#send_invitations'

    resources :users
    resources :bills

    resources :events do
      resources :participations
    end

    resources :flatmembers, only: :update

    resources :areas do
      resources :tasks
    end

    resources :chatrooms, only: [:index, :new, :create] do
      resources :messages, only: [:create]
    end

  end

  resources :bills, only: [] do
    resources :payments, only: [:update]
  end


  resources :components
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/area.rb
class Area < ApplicationRecord
  include Notifiable

  belongs_to :assigned_user, class_name: "User", optional: true
  belongs_to :previously_assigned_user, class_name: "User", optional: true
  belongs_to :flat
  has_many :tasks, dependent: :destroy

  enum category: AREA_CATEGORIES

  validates :name, presence: true
  validates :category, presence: true

  before_create :assign_user

  def assign_user
    self.assigned_user = self.flat.users.sample
  end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :update, :edit, :destroy]
  # before_action :set_users, only: [:show, :update, :edit, :destroy]
  before_action :set_tasks, only: [:show]
  skip_before_action :verify_authenticity_token, :only => [:update]

  def index
    @flat = policy_scope(Flat).find(params[:flat_id])
    @areas = Area.all
    @areas = Area.where(flat_id: params[:flat_id])
  end

  def show
    @flat = @area.flat
    authorize @area
    @notification = current_user.notifications.find_by(notifiable_id: params[:id], notifiable_type: "Area")

    if @notification
      @notification.update opened_at: Date.today
    end
  end

  def new
    @flat = policy_scope(Flat).find(params[:flat_id])
    @users = @flat.users
    @user = current_user
    @area = Area.new
  end

  def create
    @area = Area.new(area_params)
    @flat = policy_scope(Flat).find(params[:flat_id])
    @area.flat_id = @flat.id

    if @area.save
      redirect_to flat_areas_path(@flat)
    else
      render "areas/new"
    end
  end

  def edit
    @flat = @area.flat
    @users = @flat.users


    authorize @area

  end

  def update
    # flat = policy_scope(Flat).find(params[:flat_id])
    @flat = @area.flat

    if @area.update(area_params)
      redirect_to flat_area_path(@flat, @area)
    else
      redirect_to flat_areas_path(@flat)
    end

    # @area.update(area_params)
    #   respond_to do |format|
    #     format.html
    #     format.json { render json: { area: @area } }
    #   end
  end

  def destroy
    @flat = @area.flat
    @area.destroy
    authorize @area
    redirect_to flat_areas_path(@area.flat_id)
  end


  private


  def set_area
    @area = Area.find(params[:id])
  end

  def area_params
    params.require(:area).permit(:name, :category, :assigned_user_id)
  end

  def set_tasks
    @tasks = @area.tasks.all.order("created_at")
  end

  # def set_users
  #   @users = []
  #   @flat.users.each do |user|
  #     @users << "#{user.first_name}"
  #   end
  # end
end

app/views/areas/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <%= simple_form_for @area do |f| %>
        <h2>Edit Area </h2>
        <%= f.input :name,
                    placeholder: "Area's name",
                    label: false %>

        <%= f.input :category,
                    placeholder: "New Area's type",
                    label: false,
                    collection: AREA_CATEGORIES %>

        <%= f.association :assigned_user,
                    collection: @flat.users,
                    required: true,
                    label_method: :first_name,
                    include_blank: "Who is going to be resposible?",
                    label: false
                    %>

        <%= f.submit "Update area", class: "btn btn-success text-white"%>
      <% end %>
    </div>
  </div>
</div>

app/views/areas/index.html.erb
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8">
      <div class="d-flex justify-content-between align-items-center">
        <h1 class="ml-3">Tasks</h1>
        <%= link_to image_tag('add-button.svg'), new_flat_area_path %>
      </div>
    </div>
  </div>
</div>

<div class="container area">
  <% @areas.each do |area| %>
    <div class="d-flex justify-content-center border-dashed">
      <div class="col-12 col-md-8">
        <%= link_to flat_area_path(@flat, area), class: "secondary-link text-decoration-none" do %>
          <div class="d-flex justify-content-left align-items-center py-3">
            <div class="col-2">
              <% if area.name.downcase.include?(' ') %>
                <i class="<%= AREAS_ICONS[area.category.downcase.to_sym] %>"></i>
              <% else %>
                <i class="<%= AREAS_ICONS[area.category.downcase.to_sym] %>"></i>
               <% end %>
            </div>
            <div class="col-5">
                <h6 class="mb-1 d-block"><%= area.name.capitalize %></h6>

                <% if area.assigned_user.nil? %>
                  <p class="mb-0 d-block">Nobody has been assigned yet</p>
                <% else %>
                  <p class="mb-0 d-block"><%= area.assigned_user.first_name %></p>
                <% end %>
            </div>
            <div class="col-5 d-flex justify-content-end flex-wrap">
              <% area.tasks.all.each do |task| %>
                  <% if task.completed == false %>
                    <i class="tracker far fa-circle"></i>
                  <% else %>
                    <i class="tracker fas fa-circle"></i>
                  <% end %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/areas/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <%= simple_form_for [@flat, @area] do |f| %>
        <h2>Create a new Area </h2>
        <%= f.input :name,
                    placeholder: "Area's name",
                    label: false
                    %>
        <%= f.input :category,
                    required: true,
                    include_blank: "Area's type",
                    label: false,
                    collection: AREA_CATEGORIES
                      %>
        <%= f.submit "Create Area", class: "btn btn-success text-white"%>
      <% end %>
    </div>
  </div>
</div>

app/views/areas/show.html.erb
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-12 col-md-6">
      <div class="mb-3">
          <div class="d-flex justify-content-between" data-controller="tasks">
            <div
              class="mr-4"
              data-action="click->tasks#changeNameToInput"
              data-id="<%= @area.id %>"
              data-target="tasks.title"
            >
              <h1 class="mb-3">
                <%= @area.name %> tasks
              </h1>
            </div>
            <div>
              <%= link_to area_path(@area), method: :delete, data: { confirm: "Are you sure?" } do %>
                <i class="far fa-trash-alt secondary-link mr-2"></i>
              <% end %>
            </div>

          </div>

          <div class="dropdown">
            <button role="button" type="button" class="btn dropdown p-0" data-toggle="dropdown">
              Assigned to: <%= @area.assigned_user.first_name %> <%= @area.assigned_user.last_name[0] %>
            </button>
            <div class="dropdown-menu p-1 text-center" aria-labelledby="dropdownMenuButton" data-remote="true">
              <% @flat.users.each do |user| %>
                <%= simple_form_for @area, class: "dropdown-item background-none p-0 m-0", url: flat_area_path(@flat, @area), method: :patch do |f| %>
                    <%= f.input :assigned_user_id, :as => :hidden, :input_html => { :value => "#{user.id}" } %>
                    <%= f.submit "#{user.first_name}", class: "dropdown-item submit-tag p-0"%>
                <% end %>
              <% end %>
            </div>
          </div>

        <p><%= link_to "< Go to all tasks", flat_areas_path(@flat), class: "primary-link" %></p>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-6">
      <% @tasks.each do |task| %>
        <div class="task-card-white-low">
          <div class="row" id="task-<%= task.id %>">
            <div class="col-8 d-flex justify-content-start align-items-center">
              <%= link_to area_task_path(@area, task), method: :delete, remote: true, data: { confirm: "Are you sure?" } do %>
                <i class="far fa-trash-alt fa-sm mr-3"></i>
              <% end %>
              <p class="m-0 text-left"><%= task.name %></p>
            </div>
            <div class="col-4 d-flex justify-content-end align-items-center">
              <%= simple_form_for([ @area, task ], method: :patch) do |f| %>
                <%= f.input :completed, as: :hidden, input_html: { value: !task.completed }, remote: true %>
                <button class="bg-transparent border-0" style="outline: none;">
                  <% if task.completed == true %>
                    <%= image_tag 'check-done.svg' %>
                  <% else %>
                    <%= image_tag 'check-undone.svg' %>
                  <% end %>
                </button>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-12 col-md-6 text-center">
      <%= link_to image_tag('add-button.svg'), new_area_task_path(@area) %>
    </div>
  </div>
</div>